"""add phone_number to Agent

Revision ID: 7d4d841390d0
Revises: 9c25328f322f
Create Date: 2025-06-24 16:23:50.202437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d4d841390d0'
down_revision: Union[str, Sequence[str], None] = '9c25328f322f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('phone_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'phone_number')
    # ### end Alembic commands ###
