"""add cascade delete

Revision ID: d16598e2c455
Revises: 548380a83b5f
Create Date: 2025-09-21 12:58:03.946947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd16598e2c455'
down_revision: Union[str, Sequence[str], None] = '548380a83b5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cached_questions')
    op.drop_constraint(op.f('messages_conversation_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('properties_agent_id_fkey'), 'properties', type_='foreignkey')
    op.create_foreign_key(None, 'properties', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.create_foreign_key(op.f('properties_agent_id_fkey'), 'properties', 'agents', ['agent_id'], ['id'])
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_conversation_id_fkey'), 'messages', 'conversations', ['conversation_id'], ['id'])
    op.create_table('cached_questions',
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('question', name=op.f('cached_questions_pkey'))
    )
    # ### end Alembic commands ###
