"""create insight_logs table

Revision ID: 00f9cf82b86c
Revises: 25cdedf5ece8
Create Date: 2025-07-24 09:08:02.820417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
conn = op.get_bind()
insp = inspect(conn)



# revision identifiers, used by Alembic.
revision: str = '00f9cf82b86c'
down_revision: Union[str, Sequence[str], None] = '25cdedf5ece8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    if 'cached_questions' in insp.get_table_names():
        op.drop_table('cached_questions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cached_questions',
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('question', name=op.f('cached_questions_pkey'))
    )
    # ### end Alembic commands ###
