"""add insight_logs table

Revision ID: 3c9da2dfd1f0
Revises: 00f9cf82b86c
Create Date: 2025-07-24 09:19:35.644440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c9da2dfd1f0'
down_revision: Union[str, Sequence[str], None] = '00f9cf82b86c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
