"""create cached_criteria table

Revision ID: 548380a83b5f
Revises: 80a228ee1e7c
Create Date: 2025-07-24 11:22:21.010736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '548380a83b5f'
down_revision: Union[str, Sequence[str], None] = '80a228ee1e7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cached_questions')
    op.drop_table('insight_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insight_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('insight_result', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('insight_logs_agent_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('insight_logs_pkey'))
    )
    op.create_table('cached_questions',
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('question', name=op.f('cached_questions_pkey'))
    )
    # ### end Alembic commands ###
