"""insight log with agent_id as string

Revision ID: 80a228ee1e7c
Revises: 3c9da2dfd1f0
Create Date: 2025-07-24 09:22:20.537749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80a228ee1e7c'
down_revision: Union[str, Sequence[str], None] = '3c9da2dfd1f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
